[connections.2024]
url = "sqlite:///"Database/bd_sec/2024.db"

[connections.2025]
url = "sqlite:///"Database/bd_sec/2025.db"

[connections.2026]
url = "sqlite:///"Database/bd_sec/2026.db"

[connections.bandeiras_mes]
url = "sqlite:///"Database/bd_sec/bandeiras_mes.db"